#!/bin/bash

declare -i countold
countold=0
declare -i count
count=1

bash testscript &

echo "helloworld"

while [ $count -lt 11 ]; do       
    search="<maxMaps>$countold</maxMaps>"
    replace="<maxMaps>$count</maxMaps>"
    grep $search conf/fair-scheduler.xml

    sed -i "5s|.*|$replace|g" conf/fair-scheduler.xml
    countold=$count
    count=$count+1
    echo $count
    sleep 50s           
done

echo "Hello World!"
